### ISSUE TITLE
load module error

### ISSUE THREAD

**Issue by batkiz** [liuzijing97/scoop-auto-completion#17] opened 2019-12-26 17:19 UTC
## versions
powershell core 7.0.0-rc1 and powershell 5.1
scoop-completion 0.2.2 installed via [Ash258 bucket](https://github.com/Ash258/scoop-Ash258)

## error
i import this module in my `$PROFILE`, everytime i open powershell, it will appear the errors as follow:
```ps1
Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-IsReadOnly.ps1'        | because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-IsReadOnly.ps1'
     | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-IsFixedSize.ps1'       | because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-IsFixedSize.ps1'      | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path
     | 'C:\soft\Scoop\shims\scoop-IsSynchronized.ps1' because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path
     | 'C:\soft\Scoop\shims\scoop-IsSynchronized.ps1' because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Keys.ps1' because      | it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Keys.ps1'             | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Values.ps1'            | because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Values.ps1'           | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-SyncRoot.ps1'          | because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-SyncRoot.ps1'         | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.

Get-Content: C:\soft\Scoop\apps\scoop\current\lib\commands.ps1
Line |
  22 |         $line = ((Get-Content $shim_path) | Where-Object { $_.startswith('$path') })
     |                   ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Count.ps1'
     | because it does not exist.

Get-Content: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  91 |         $content = Get-Content (command_path $_.Name)
     |                    ^ Cannot find path 'C:\soft\Scoop\shims\scoop-Count.ps1'            | because it does not exist.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  92 |         $command = ($content | Select-Object -Skip 1).Trim()
     |         ^ You cannot call a method on a null-valued expression.

InvalidOperation: C:\soft\Scoop\apps\scoop\current\libexec\scoop-alias.ps1
Line |
  93 |         $summary = (summary $content).Trim()
     |         ^ You cannot call a method on a null-valued expression.
```

**Comment by Moeologist** [comment] 2019-12-29 09:12
duplicate of #13

**Closed as completed by Moeologist** 2019-12-29 09:12 UTC
Labels: duplicate
