### ISSUE TITLE
I am getting error first time i start up powershell console 

### ISSUE THREAD

**Issue by GamerClassN7** [liuzijing97/scoop-auto-completion#19] opened 2020-04-12 19:36 UTC
![image](https://user-images.githubusercontent.com/22167469/79078020-b26cba80-7d05-11ea-8735-be3930c42c3f.png)

**Comment by Moeologist** [comment] 2020-04-14 05:31
duplicate of #13

**Closed as completed** 2020-05-15 13:17 UTC
Labels: duplicate
